// Generated by Fairy on 2025-04-22  19:20

/*!INCLUDES_BEGIN!*/
#include "ui.hpp"
#include <cstring>
/*!INCLUDES_END!*/

// 组件定义 
namespace gui::widgets::main 
{
	Image img_screen_img_1;
	Chart chart_screen_chart_1;
	Button btn_screen_btn_3;
	Label label_screen_btn_3_label;
	Label label_screen_label_h2_data;
	Label label_screen_label_h2;
	Label label_screen_label_h3;
	Label label_screen_label_h3_data;
	Label label_screen_label_h4;
	Label label_screen_label_h4_data;
	Label label_screen_label_thd;
	Label label_screen_label_thd_data;
	Label label_screen_label_h5;
	Label label_screen_label_h5_data;
	Label label_screen_label_freq;
	Label label_screen_label_freq_data;
	Label label_screen_label_h1;
	Label label_screen_label_h1_data;
	Label label_screen_label_x;
	Label label_screen_label_x_data;
	Label label_screen_label_y;
	Label label_screen_label_y_data;
/*!WIDGETS_DEFINE_BEGIN!*/
    Dropdown dropdown_screen_dropdown_1;
/*!WIDGETS_DEFINE_END!*/
}
using namespace gui::widgets::main;


/*!DECLARE_CODE_BEGIN!*/
// 全局变量定义
// 类声明
class THD
{
public:
    static auto initChartComponent() -> void;
    static inline auto initDropDownComponent() -> void;
    // 生成随机数据
    static inline auto generate_data(int32_t* pool)->void;
    static inline auto generate_text(float* normal_pool,float thd,float div,float fundamental_freq)->void;
    static inline auto clear_text()->void;
    static inline auto toggle_generation() -> void;
    static inline auto get_generate_state() -> bool;
    static inline auto get_chart_type() -> int;
public:
    static inline auto set_cursor_on_press()->void
    {
        chart_screen_chart_1.set_cursor_pos_on_pressed(cursor);
        if(had_generated)
        {
            char buf_x[10];
            char buf_y[10];
//            lv_snprintf(buf, sizeof(buf), "%d %d",chart_screen_chart_1.get_pressed_point(), chart_screen_chart_1.get_cursor_point_y(series));//格式化点数值成字符串
            sprintf(buf_x, "%ld", chart_screen_chart_1.get_pressed_point());
            sprintf(buf_y, "%ld", chart_screen_chart_1.get_cursor_point_y(series));
            label_screen_label_x_data.text(buf_x);
            label_screen_label_y_data.text(buf_y);
        }
    }

    static inline auto set_chart_type() -> void
    {
        if (dropdown_screen_dropdown_1.getSelected() == 0)
        {
            chart_type=0;
            chart_screen_chart_1.point_count(24);
        }
        if (dropdown_screen_dropdown_1.getSelected() == 1)
        {
            chart_type=1;
            chart_screen_chart_1.point_count(128);
        }

    }
    static inline bool had_generated = false;
private:
    // 添加生成状态标志
    static inline bool is_generating = false;
    static  inline  ChartSeries_t series{}; //数据 系列
    static  inline  ChartCursor_t cursor{}; //光标 系列1
    static  inline  lv_point_t cursor_point{}; //光标 系列1
    static  inline constexpr   uint32_t point_count=24;
    static  inline int chart_type=0;
};
// 类声明

/*!DECLARE_CODE_END!*/


namespace gui::init
{
    void screen() 
    {
		scr.bg_color(lv_color_hex(0xffffff))
			.bg_grad_dir(LV_GRAD_DIR_NONE);

		img_screen_img_1.init()
			.pos(389, 7)
			.size(83, 55)
			.add_flag(LV_OBJ_FLAG_CLICKABLE)
			.src(&_dianzisheji_RGB565A8_83x55)
			.pivot(50, 50)
			.image_recolor_opa(0);

		chart_screen_chart_1.init()
			.pos(2, 79)
			.size(341, 236)
			.scrollbar_mode(LV_SCROLLBAR_MODE_OFF)
			.div_count(11, 15)
			.point_count(5)
			.range(LV_CHART_AXIS_PRIMARY_Y)
			.range(LV_CHART_AXIS_SECONDARY_Y)
			.bg_color(lv_color_hex(0xffffff))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.border_width(1)
			.border_opa(255)
			.border_color(lv_color_hex(0xFFFFFF))
			.border_side(LV_BORDER_SIDE_FULL)
			.radius(0)
			.line_width(2)
			.line_color(lv_color_hex(0xe8e8e8));

		btn_screen_btn_3.init()
			.pos(29, 29)
			.size(51, 32)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_3_label.init(btn_screen_btn_3)
			.text("测量")
			.center()
			.width(LV_PCT(100));

		label_screen_label_h2_data.init()
			.pos(418, 193)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h2.init()
			.pos(354, 193)
			.size(49, 19)
			.text("H2/H1")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h3.init()
			.pos(354, 223)
			.size(49, 19)
			.text("H3/H1")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h3_data.init()
			.pos(418, 223)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h4.init()
			.pos(354, 253)
			.size(49, 19)
			.text("H4/H1")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h4_data.init()
			.pos(418, 253)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_thd.init()
			.pos(354, 163)
			.size(49, 19)
			.text("THD")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_thd_data.init()
			.pos(418, 163)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h5.init()
			.pos(354, 283)
			.size(49, 19)
			.text("H5/H1")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h5_data.init()
			.pos(418, 283)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_freq.init()
			.pos(354, 102)
			.size(52, 19)
			.text("采样率")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_freq_data.init()
			.pos(408, 102)
			.size(68, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h1.init()
			.pos(354, 132)
			.size(52, 19)
			.text("频率")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_h1_data.init()
			.pos(418, 135)
			.size(49, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_x.init()
			.pos(255, 19)
			.size(13, 19)
			.text("X:")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_x_data.init()
			.pos(274, 19)
			.size(71, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.bg_opa(0);

		label_screen_label_y.init()
			.pos(255, 48)
			.size(13, 19)
			.text("Y:")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.bg_opa(0);

		label_screen_label_y_data.init()
			.pos(274, 48)
			.size(77, 19)
			.text("0")
			.radius(0)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.bg_opa(0);
    /*!INIT_CUSTOM_BEGIN!*/

        THD::initChartComponent();
        THD::initDropDownComponent();
    /*!INIT_CUSTOM_END!*/
    }
    
    void events()
    {
    /*!EVENTS_CUSTOM_BEGIN!*/
        widgets::main::btn_screen_btn_3.OnClicked<THD::toggle_generation>();
        widgets::main::chart_screen_chart_1.OnPressed<THD::set_cursor_on_press>();
        widgets::main::dropdown_screen_dropdown_1.OnValueChanged<THD::set_chart_type>();


    /*!EVENTS_CUSTOM_END!*/
    }
}



/*!UI_IMPLEMENT_BEGIN!*/
// 用户自定义接口实现区（安全编辑区） 
namespace gui::interface::ui {

    // 生成图表数据外部接口
    void gui_generate_chart_data(int32_t* data_pool)
    {
        THD::generate_data(data_pool);
    }
    // 生成谐波数据外部接口
    void gui_generate_text_data(float* text_data,float thd,float div,float fundamental_freq)
    {
        THD::generate_text(text_data,thd,div,fundamental_freq);
    }

    void gui_clear_text_data()
    {
        THD::clear_text();
    }
    bool start_fft()
    {
        return THD::get_generate_state();
    }
    void stop_fft()
    {
        THD::toggle_generation();
    }
    //获取图表类型
    int gui_get_chart_type()
    {
        return THD::get_chart_type();
    }


}
/*!UI_IMPLEMENT_END!*/


/*!DEFINE_CODE_BEGIN!*/
// 类定义
auto THD::initChartComponent() -> void
{
    series=chart_screen_chart_1.update_mode(LV_CHART_UPDATE_MODE_SHIFT)  // 改为SHIFT模式
            .line_color(lv_color_hex(0x000000))
            .point_count(point_count)
            .remove_dot()
            .add_series(lv_color_hex(0x34e6ff))
            ;

    chart_screen_chart_1
            .line_color(lv_color_hex(0x808080))
            .bg_color(lv_color_hex(0x000000))
            .range(LV_CHART_AXIS_PRIMARY_Y, 0, 4095)
            ;

    cursor=chart_screen_chart_1.add_cursor(lv_color_hex(0x0bce11),LV_DIR_ALL);
//    scale_screen_scale_1.border_opa(0);
}
auto THD::initDropDownComponent() -> void
{
    dropdown_screen_dropdown_1.init()
            .pos(98, 29)
            .size(141, 33)
            .text(nullptr)
            .options("示波器\n频谱仪")
            .bg_color(lv_color_hex(0xFFFFFF))
            .font(&lv_customer_font_SourceHanSerifSC_Regular_13)
            .direction(LV_DIR_BOTTOM)
            .selected(0)
            .border_color(lv_color_hex(0x57b4e5))
            .symbol("▼"); // 文本符号


    static lv_style_t style_screen_ddlist_1_extra_list_main_default;
    if (style_screen_ddlist_1_extra_list_main_default.prop_cnt > 1)
        lv_style_reset(&style_screen_ddlist_1_extra_list_main_default);
    else
        lv_style_init(&style_screen_ddlist_1_extra_list_main_default);

    lv_style_set_max_height(&style_screen_ddlist_1_extra_list_main_default, 90);
    lv_style_set_text_color(&style_screen_ddlist_1_extra_list_main_default, lv_color_hex(0x0D3055));
    lv_style_set_text_font(&style_screen_ddlist_1_extra_list_main_default,
                           &lv_customer_font_SourceHanSerifSC_Regular_13);
    lv_style_set_text_opa(&style_screen_ddlist_1_extra_list_main_default, 255);
    lv_style_set_border_width(&style_screen_ddlist_1_extra_list_main_default, 1);
    lv_style_set_border_opa(&style_screen_ddlist_1_extra_list_main_default, 255);
    lv_style_set_border_color(&style_screen_ddlist_1_extra_list_main_default, lv_color_hex(0xe1e6ee));
    lv_style_set_border_side(&style_screen_ddlist_1_extra_list_main_default, LV_BORDER_SIDE_FULL);
    lv_style_set_radius(&style_screen_ddlist_1_extra_list_main_default, 3);
    lv_style_set_bg_opa(&style_screen_ddlist_1_extra_list_main_default, 255);
    lv_style_set_bg_color(&style_screen_ddlist_1_extra_list_main_default, lv_color_hex(0xffffff));
    lv_style_set_bg_grad_dir(&style_screen_ddlist_1_extra_list_main_default, LV_GRAD_DIR_NONE);
    lv_obj_add_style(lv_dropdown_get_list(dropdown_screen_dropdown_1), &style_screen_ddlist_1_extra_list_main_default,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
auto THD::generate_data(int32_t* pool)->void
{
    chart_screen_chart_1.ext_y_array(series, pool);
}
auto THD::generate_text(float* normal_pool,float thd,float div,float fundamental_freq)->void
{
    char bufthd[10];
    char bufdiv[10];
    char buf_freq[10];
    char buf1[10];
    char buf2[10];
    char buf3[10];
    char buf4[10];
    char bufx[10];
    char bufy[10];

//    lv_snprintf(bufthd, sizeof(bufthd), "%.4f",thd);//格式化点数值成字符串
//    lv_snprintf(buf1, sizeof(buf1), "",normal_pool[1]);//格式化点数值成字符串
//    lv_snprintf(buf2, sizeof(buf2), "%.4f",normal_pool[2]);//格式化点数值成字符串
//    lv_snprintf(buf3, sizeof(buf3), "%.4f",normal_pool[3]);//格式化点数值成字符串
//    lv_snprintf(buf4, sizeof(buf4), "%.4f",normal_pool[4]);//格式化点数值成字符串

    sprintf(bufthd, "%.1f%%", thd);          // 格式化 thd，保留四位小数
    sprintf(bufdiv, "%.1f", div); // 格式化 div, 保留一位小数
    sprintf(buf_freq, "%.1f", fundamental_freq); // 格式化 normal_pool[1]，保留四位小数
    sprintf(buf1, "%.4f", normal_pool[2]); // 格式化 normal_pool[1]，保留四位小数
    sprintf(buf2, "%.4f", normal_pool[3]); // 格式化 normal_pool[2]，保留四位小数
    sprintf(buf3, "%.4f", normal_pool[4]); // 格式化 normal_pool[3]，保留四位小数
    sprintf(buf4, "%.4f", normal_pool[5]); // 格式化 normal_pool[4]，保留四位小数


    label_screen_label_freq_data.text(bufdiv);
    label_screen_label_thd_data.text(bufthd);
    label_screen_label_h1_data.text(buf_freq);
    label_screen_label_h2_data.text(buf1);
    label_screen_label_h3_data.text(buf2);
    label_screen_label_h4_data.text(buf3);
    label_screen_label_h5_data.text(buf4);

}
auto THD::clear_text()->void
{
    label_screen_label_freq_data.text("-");
    label_screen_label_thd_data.text("-");
    label_screen_label_h1_data.text("-");
    label_screen_label_h2_data.text("-");
    label_screen_label_h3_data.text("-");
    label_screen_label_h4_data.text("-");
    label_screen_label_h5_data.text("-");
}

// 新增切换生成状态的方法
auto THD::toggle_generation() -> void
{
    is_generating = !is_generating;
    had_generated=true;

}

// 获取图表类型
auto THD::get_chart_type() -> int
{
    return chart_type;
}
// 获取生成数据状态
auto THD::get_generate_state() -> bool
{
    return is_generating ;
}

/*!DEFINE_CODE_END!*/
