// Generated by Fairy on 2025-04-21  21:11

// Auto-generated UI Code, converted from GUI Guider
#include "GUI_Base.hpp"
 
namespace gui::widgets::main
{
	extern 	Image img_screen_img_1;
	extern 	Chart chart_screen_chart_1;
	extern 	Button btn_screen_btn_3;
	extern 	Label label_screen_btn_3_label;
	extern 	Label label_screen_label_h2_data;
	extern 	Label label_screen_label_h2;
	extern 	Label label_screen_label_h3;
	extern 	Label label_screen_label_h3_data;
	extern 	Label label_screen_label_h4;
	extern 	Label label_screen_label_h4_data;
	extern 	Label label_screen_label_thd;
	extern 	Label label_screen_label_thd_data;
	extern 	Label label_screen_label_h5;
	extern 	Label label_screen_label_h5_data;
	extern 	Label label_screen_label_freq;
	extern 	Label label_screen_label_freq_data;
	extern 	Label label_screen_label_h1;
	extern 	Label label_screen_label_h1_data;
/*!WIDGETS_DECLARE_BEGIN!*/
    extern 	Dropdown dropdown_screen_dropdown_1;
/*!WIDGETS_DECLARE_END!*/
}  


// ------定义UI接口------
/*!UI_INTERFACE_BEGIN!*/
#include "ui_interface.hpp"
// 用户自定义接口声明区（安全编辑区）
namespace gui::interface::ui {
    void gui_generate_chart_data(int32_t* data_pool);
    void gui_generate_text_data(float* text_data,float thd,float div,float fundamental_freq);
    void gui_clear_text_data();
    bool start_fft();
    void stop_fft();
    int gui_get_chart_type();
}
/*!UI_INTERFACE_END!*/


// ------加载资源------
//  字体资源
LV_FONT_DECLARE(lv_customer_font_SourceHanSerifSC_Regular_13)
//  图片资源
LV_IMG_DECLARE(_dianzisheji_RGB565A8_83x55)  
