config:
  strict_mode: false  # 未匹配规则时是否报错（true=严格模式，false=保留原代码）

  # 跳过规则（有些函数直接跳过）
skip_rules:
  variables:
  calls:
    - lv_obj_update_layout

mappings:
  # 变量类型映射（C类型 → C++类型）
  variable_types:
    lv_obj_create: Component
    lv_label_create: Label
    lv_btn_create: Button

  # 样式函数映射（特殊映射）
  style_calls:
    border_width: "0"
    radius: "0"
    text_color: "lv_color_hex(0x000000)"
    text_opa: "255"
    text_letter_space: "0"
    text_line_space: "0"
    bg_opa: "lv_color_hex(0xffffff)" # 默认缺省表，如果满足，则省略调用
    bg_color: "lv_color_hex(0xffffff)"
    pad_top: "0"
    pad_right:  "0"
    pad_bottom: "0"
    pad_left: "0"
    shadow_width: "0"
    image_recolor_opa: "0"
    image_opa: "255"
    border_side: "LV_BORDER_SIDE_FULL"
    line_width: "0"
    line_opa: "255"
    bg_grad_dir: "LV_GRAD_DIR_NONE"
    border_opa: "255"
    # 没有默认值
    text_align: None
    line_color: None
    border_color: None




  # 函数调用映射（普通映射）
  function_calls:
    lv_obj_set_pos:
      name: "pos"   # 重新映射后的方法名

    lv_obj_set_size:
      name: "size"

    lv_label_set_long_mode:
      name: "text_long_mode"
      optional: ture
      defaults: ["LV_LABEL_LONG_WRAP"]

    lv_image_set_rotation:
      name: "img_rotation"
      optional: true
      defaults: ["0"]

    lv_chart_set_range:
      name: "chart_range"
      optional: true
      defaults: ["LV_CHART_AXIS_PRIMARY_Y","0","100"] # 不止一个参数为默认值，后面可以扩展
      defaults2: ["LV_CHART_AXIS_SECONDARY_Y","0","100"]# 次缺省表，只有当前面的失效后才会生效

    lv_obj_set_scrollbar_mode:
      name: "scrollbar_mode"
      optional: true
      defaults: ["LV_SCROLLBAR_MODE_OFF"]

    lv_obj_align:
      name: "align"
      optional: false # 是否允许省略调用（如果参数均为默认值），不填或者添false表示不允许
      defaults: [0,0]
      naming_rule:
        source_arg: 1
        pattern:
          "LV_ALIGN_CENTER": "center"




