// Generated by Fairy on 2025-02-26  23:00

/*!INCLUDES_BEGIN!*/
#include "ui.hpp"

/*!INCLUDES_END!*/

// 组件定义 
namespace gui::widgets::main 
{
	Button btn_screen_btn_1;
	Label label_screen_btn_1_label;
	Button btn_screen_btn_2;
	Label label_screen_btn_2_label;
	ImageButton imgbtn_screen_imgbtn_1;
	Label label_screen_imgbtn_1_label;
	Roller roller_screen_roller_1;
/*!WIDGETS_DEFINE_BEGIN!*/

/*!WIDGETS_DEFINE_END!*/
}
using namespace gui::widgets::main;


/*!DECLARE_CODE_BEGIN!*/
// 全局变量定义

// 类声明

/*!DECLARE_CODE_END!*/


namespace gui::init
{
    void screen() 
    {
		scr.bg_color(lv_color_hex(0xffffff))
			.bg_grad_dir(LV_GRAD_DIR_NONE);

		btn_screen_btn_1.init()
			.pos(74, 76)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_1_label.init(btn_screen_btn_1)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		btn_screen_btn_2.init()
			.pos(291, 76)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_2_label.init(btn_screen_btn_2)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		imgbtn_screen_imgbtn_1.init()
			.pos(186, 7)
			.size(95, 69)
			.checkable()
			.pressed_src(&_12345678_RGB565A8_95x69)
			.pad_all(0, LV_STATE_DEFAULT)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.shadow_width(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.text_color(lv_color_hex(0xFF33FF), static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.font(&lv_font_montserratMedium_12, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.text_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.shadow_width(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.text_color(lv_color_hex(0xFF33FF), static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.font(&lv_font_montserratMedium_12, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.text_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_IMAGEBUTTON_STATE_RELEASED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_IMAGEBUTTON_STATE_RELEASED));

		label_screen_imgbtn_1_label.init(imgbtn_screen_imgbtn_1)
			.text("")
			.center();

		roller_screen_roller_1.init()
			.pos(186, 153)
			.width(100)
			.options("1\n2\n3\n4\n5", LV_ROLLER_MODE_NORMAL)
			.radius(5)
			.bg_color(lv_color_hex(0xffffff))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.text_color(lv_color_hex(0x333333))
			.font(&lv_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.border_width(2)
			.border_opa(255)
			.border_color(lv_color_hex(0xe6e6e6))
			.border_side(LV_BORDER_SIDE_FULL)
			.bg_opa(255, static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.bg_color(lv_color_hex(0x2195f6), static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.bg_grad_dir(LV_GRAD_DIR_NONE, static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.text_color(lv_color_hex(0xFFFFFF), static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.font(&lv_font_montserratMedium_12, static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.text_opa(255, static_cast<int>(LV_PART_SELECTED)|static_cast<int>(LV_STATE_DEFAULT))
			.VisibleRowCount(5);
    /*!INIT_CUSTOM_BEGIN!*/

    /*!INIT_CUSTOM_END!*/
    }
    
    void events()
    {
    /*!EVENTS_CUSTOM_BEGIN!*/
    
    /*!EVENTS_CUSTOM_END!*/
    }
}



/*!UI_IMPLEMENT_BEGIN!*/
// 用户自定义接口实现区（安全编辑区） 
namespace gui::interface {


}
/*!UI_IMPLEMENT_END!*/


/*!DEFINE_CODE_BEGIN!*/
// 类定义

/*!DEFINE_CODE_END!*/
