// Generated by Fairy on 2025-02-25  23:13

/*!INCLUDES_BEGIN!*/
#include "ui.hpp"

/*!INCLUDES_END!*/

// 组件定义 
namespace gui::widgets::main 
{
	Button btn_screen_btn_1;
	Label label_screen_btn_1_label;
	Button btn_screen_btn_2;
	Label label_screen_btn_2_label;
	Button btn_screen_btn_3;
	Label label_screen_btn_3_label;
	Button btn_screen_btn_4;
	Label label_screen_btn_4_label;
	ImageButton imgbtn_screen_imgbtn_1;
	Label label_screen_imgbtn_1_label;
/*!WIDGETS_DEFINE_BEGIN!*/

/*!WIDGETS_DEFINE_END!*/
}
using namespace gui::widgets::main;


/*!DECLARE_CODE_BEGIN!*/
// 全局变量定义

// 类声明

/*!DECLARE_CODE_END!*/


namespace gui::init
{
    void screen() 
    {
		scr.bg_color(lv_color_hex(0xffffff))
			.bg_grad_dir(LV_GRAD_DIR_NONE);

		btn_screen_btn_1.init()
			.pos(86, 50)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_1_label.init(btn_screen_btn_1)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		btn_screen_btn_2.init()
			.pos(256, 50)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_2_label.init(btn_screen_btn_2)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		btn_screen_btn_3.init()
			.pos(86, 140)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_3_label.init(btn_screen_btn_3)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		btn_screen_btn_4.init()
			.pos(262, 144)
			.size(100, 50)
			.pad_all(0, LV_STATE_DEFAULT)
			.bg_color(lv_color_hex(0x2195f6))
			.bg_grad_dir(LV_GRAD_DIR_NONE)
			.radius(5)
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER);

		label_screen_btn_4_label.init(btn_screen_btn_4)
			.text("Button")
			.center()
			.width(LV_PCT(100));

		imgbtn_screen_imgbtn_1.init()
			.pos(170, 97)
			.size(100, 50)
			.checkable()
			.pressed_src(&_12345678_RGB565A8_100x50)
			.pad_all(0, LV_STATE_DEFAULT)
			.text_color(lv_color_hex(0x000000))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13)
			.text_align(LV_TEXT_ALIGN_CENTER)
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.text_color(lv_color_hex(0xFF33FF), static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.text_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.shadow_width(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_PRESSED))
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.text_color(lv_color_hex(0xFF33FF), static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.font(&lv_customer_font_SourceHanSerifSC_Regular_13, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.text_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.shadow_width(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_STATE_CHECKED))
			.image_recolor_opa(0, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_IMAGEBUTTON_STATE_RELEASED))
			.image_opa(255, static_cast<int>(LV_PART_MAIN)|static_cast<int>(LV_IMAGEBUTTON_STATE_RELEASED));

		label_screen_imgbtn_1_label.init(imgbtn_screen_imgbtn_1)
			.text("")
			.center();
    /*!INIT_CUSTOM_BEGIN!*/

    /*!INIT_CUSTOM_END!*/
    }
    
    void events()
    {
    /*!EVENTS_CUSTOM_BEGIN!*/
    
    /*!EVENTS_CUSTOM_END!*/
    }
}



/*!UI_IMPLEMENT_BEGIN!*/
// 用户自定义接口实现区（安全编辑区） 
namespace gui::interface {


}
/*!UI_IMPLEMENT_END!*/


/*!DEFINE_CODE_BEGIN!*/
// 类定义

/*!DEFINE_CODE_END!*/
