// Generated by Fairy on 2025-02-27  21:20

// Auto-generated UI Code, converted from GUI Guider
#include "GUI_Base.hpp"
 
namespace gui::widgets::main
{
	extern 	Image img_screen_img_1;
	extern 	Chart chart_screen_chart_1;
	extern 	Button btn_screen_btn_1;
	extern 	Label label_screen_btn_1_label;
	extern 	Button btn_screen_btn_2;
	extern 	Label label_screen_btn_2_label;
	extern 	Button btn_screen_btn_3;
	extern 	Label label_screen_btn_3_label;
	extern 	Button btn_screen_btn_4;
	extern 	Label label_screen_btn_4_label;
	extern 	Button btn_screen_btn_5;
	extern 	Label label_screen_btn_5_label;
	extern 	Slider slider_screen_slider_1;
	extern 	Label label_screen_label_1;
	extern 	Label label_screen_label_2;
	extern 	Button btn_screen_btn_6;
	extern 	Label label_screen_btn_6_label;
	extern 	Button btn_screen_btn_7;
	extern 	Label label_screen_btn_7_label;
	extern 	Label label_screen_label_3;
/*!WIDGETS_DECLARE_BEGIN!*/

/*!WIDGETS_DECLARE_END!*/
}  


// ------定义UI接口------
/*!UI_INTERFACE_BEGIN!*/
// 用户自定义接口声明区（安全编辑区）
namespace gui::interface {


}
/*!UI_INTERFACE_END!*/


// ------加载资源------
//  字体资源
LV_FONT_DECLARE(lv_customer_font_SourceHanSerifSC_Regular_13)
//  图片资源
LV_IMG_DECLARE(_dianzisheji_RGB565A8_61x42)  
