// Generated by Fairy on 2025-02-25  23:13

// Auto-generated UI Code, converted from GUI Guider
#include "GUI_Base.hpp"
 
namespace gui::widgets::main
{
	extern 	Button btn_screen_btn_1;
	extern 	Label label_screen_btn_1_label;
	extern 	Button btn_screen_btn_2;
	extern 	Label label_screen_btn_2_label;
	extern 	Button btn_screen_btn_3;
	extern 	Label label_screen_btn_3_label;
	extern 	Button btn_screen_btn_4;
	extern 	Label label_screen_btn_4_label;
	extern 	ImageButton imgbtn_screen_imgbtn_1;
	extern 	Label label_screen_imgbtn_1_label;
/*!WIDGETS_DECLARE_BEGIN!*/

/*!WIDGETS_DECLARE_END!*/
}  


// ------定义UI接口------
/*!UI_INTERFACE_BEGIN!*/
// 用户自定义接口声明区（安全编辑区）
namespace gui::interface {


}
/*!UI_INTERFACE_END!*/


// ------加载资源------
//  字体资源
LV_FONT_DECLARE(lv_customer_font_SourceHanSerifSC_Regular_13)
LV_FONT_DECLARE(lv_customer_font_montserratMedium_12)
//  图片资源
LV_IMG_DECLARE(_12345678_RGB565A8_100x50)  
