//
// Created by 34753 on 2024/10/7.
//

#ifndef FURINA_KEYTASKHANDLER_HPP
#define FURINA_KEYTASKHANDLER_HPP
#include "JYZQ_Conf.h"
#if ENABLE_KEY_TASK_HANDLE
#include "key.hpp"



#endif// ENABLE_KEY_TASK_HANDLE
#endif //FURINA_KEYTASKHANDLER_HPP
