// Generated by Fairy on 2025-02-14  14:39

// Auto-generated UI Code, converted from GUI Guider
#include "GUI_Base.hpp"
 
namespace gui::widgets::main
{
	extern 	Component obj_blueCounter_cont_1;
	extern 	ImageButton imgbtn_blueCounter_plus;
	extern 	Label label_blueCounter_plus_label;
	extern 	ImageButton imgbtn_blueCounter_minus;
	extern 	Label label_blueCounter_minus_label;
	extern 	Button btn_blueCounter_btn_1;
	extern 	Label label_blueCounter_btn_1_label;
	extern 	Image img_blueCounter_logo;
	extern 	Label label_blueCounter_counter;
	extern 	CheckBox chekcbox_blueCounter_cb_1;
}  


// 定义UI接口
namespace gui::interface
{

}

// 加载资源
  
