// Generated by Fairy on 2025-02-14  20:50

// Auto-generated UI Code, converted from GUI Guider
#include "GUI_Base.hpp"
 
namespace gui::widgets::main
{
	extern 	Component obj_blueCounter_cont_1;
	extern 	ImageButton imgbtn_blueCounter_plus;
	extern 	Label label_blueCounter_plus_label;
	extern 	ImageButton imgbtn_blueCounter_minus;
	extern 	Label label_blueCounter_minus_label;
	extern 	Button btn_blueCounter_btn_1;
	extern 	Label label_blueCounter_btn_1_label;
	extern 	Image img_blueCounter_logo;
	extern 	Label label_blueCounter_counter;
	extern 	CheckBox chekcbox_blueCounter_cb_1;
	extern 	Image img_blueCounter_img_1;
	extern 	Label label_blueCounter_label_1;
/*!WIDGETS_DECLARE_BEGIN!*/

/*!WIDGETS_DECLARE_END!*/
}  


// ------定义UI接口------
/*!UI_INTERFACE_BEGIN!*/
// 用户自定义接口声明区（安全编辑区）
namespace gui::interface {


}
/*!UI_INTERFACE_END!*/


// ------加载资源------
//  字体资源
LV_FONT_DECLARE(lv_font_arial_34)
LV_FONT_DECLARE(lv_font_montserratMedium_34)
LV_FONT_DECLARE(lv_font_montserratMedium_16)
LV_FONT_DECLARE(lv_font_arial_40)
LV_FONT_DECLARE(lv_font_SourceHanSerifSC_Regular_16)
//  图片资源
LV_IMG_DECLARE(_btn_RGB565A8_65x65)
LV_IMG_DECLARE(_NXP_Logo_RGB565A8_60x34)  
